spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
logging:
  level:
    pl.polona: DEBUG
server:
  port: ${PORT:8080}
app:
  jwt-secret: JWTSuperSecretKey
  jwt-expiration-in-ms: 604800000
